### Travis CI Integration

# We will test C, C++, C++03/11 and Java. So we need Java installed.
language: java

install:
    # Install libxml2 for XML validation.
    - wget ftp://xmlsoft.org/libxml2/LATEST_LIBXML2
    - tar xf LATEST_LIBXML2 && cd libxml2*
    - ./configure && make
    - export XMLLINT_PATH=$(pwd)/
    - cd ..

    # Install RTI Connext DDS core host and target
    - wget -q $DOWNLOAD520_HOST
    - wget -q $DOWNLOAD520_TARGET
    - chmod +x rti*.run
    - ./rti*.run --mode unattended --unattendedmodeui none
    - export NDDSHOME=$HOME/rti_connext_dds-5.2.0
    - export LD_LIBRARY_PATH=$NDDSHOME/lib/x64Linux3.xgcc4.6.3:$LD_LIBRARY_PATH
    - $NDDSHOME/bin/rtipkginstall -u *.rtipkg

script:
    # Check XML
    - perl resources/scripts/xml_validation.pl examples 5.2.0

    # Compile examples
    - perl resources/scripts/compile_unix.pl ./examples 5.2.0 x64Linux3.xgcc4.6.3
